# Generated by Django 5.2.8 on 2025-12-05 12:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='certifications',
            field=models.CharField(blank=True, help_text='e.g. Fair Trade, Organic, Rainforest Alliance', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='core_products',
            field=models.CharField(blank=True, help_text='e.g. Green Beans, Arabica, Robusta', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Short bio about your coffee business', max_length=500),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
