# Generated by Django 5.2.8 on 2025-12-05 12:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_sellerprofile_certifications_sellerprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fair Trade', 'Fair Trade International'), ('USDA Organic', 'USDA Organic'), ('Rainforest', 'Rainforest Alliance'), ('UTZ', 'UTZ Certified'), ('Bird Friendly', 'Bird Friendly (Smithsonian)'), ('C.A.F.E.', 'C.A.F.E. Practices (Starbucks)'), ('Other', 'Other / Local Government')], max_length=50)),
                ('document_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('authority_name', models.CharField(help_text='Who issued this? (e.g., Control Union)', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='market.sellerprofile')),
            ],
        ),
    ]
