# Generated by Django 5.2.8 on 2025-12-04 07:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdoc',
            name='business_license',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='business_license'),
        ),
        migrations.AlterField(
            model_name='verificationdoc',
            name='id_card',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_card'),
        ),
    ]
