# Generated by Django 5.2.8 on 2025-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_verificationdoc_business_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='package_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('professional', 'Professional')], default='basic', max_length=15),
        ),
    ]
